# Generated by Django 2.1.3 on 2018-11-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=30)),
                ('player_two', models.CharField(max_length=30)),
                ('score_one', models.IntegerField()),
                ('score_two', models.IntegerField()),
            ],
        ),
    ]
