version: '3.7'
services:
    scorekeeper:
        image: "scorekeeper-service"
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ..:/app
        environment:
            DJANGO_DEBUG: "true"
            DJANGO_SECRET_KEY: foobar
            DJANGO_ALLOWED_HOSTS: "*"
        ports:
            - "1003:80"
